# Generated by Django 5.1.3 on 2024-12-06 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_price_per_day_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
