# Generated by Django 5.1.3 on 2024-12-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='booking',
        ),
    ]
