# Generated by Django 5.1.4 on 2025-03-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_remove_review_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
